import = [
    "~/.config/alacritty/themes/themes/argonaut.toml"
]

[env]
  TERM = "xterm-256color"

[window]
 opacity = 0.8
 padding = { x = 10, y = 10}
 startup_mode = "Maximized"
 decorations = "None"

[[hints.enabled]]
 command = "xdg-open"
 hyperlinks = true
 post_processing = true
 mouse.enabled = true
 regex = "(https://|http://|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[font]
size=12
normal.family = "MesloLGS Nerd Font Mono"

